"""
Deterministic draft generator — no LLM required.

Builds sections only in allowed sentence classes from structured inputs.
"""
from __future__ import annotations

from collections import Counter
from typing import Any, Dict, List, Optional

from witness_light.core.models import ALLOWED_CLASSES, DraftReport, ReportSection
from witness_light.policy.lexical import check_text


def list_sentence_classes() -> List[str]:
    return list(ALLOWED_CLASSES)


def _obs_from_event(ev: Dict[str, Any]) -> ReportSection:
    summary = str(ev.get("summary") or ev.get("type") or "event")[:200]
    when = ev.get("when_label") or ""
    if not when and ev.get("when_ms"):
        when = f"unix_ms={ev.get('when_ms')}"
    tool = ev.get("tool") or ""
    text = f"Observed record of type {ev.get('type', 'unknown')}: {summary}."
    if when:
        text = f"At {when}, observed record of type {ev.get('type', 'unknown')}: {summary}."
    refs = [str(ev.get("obs_id") or "")]
    if tool:
        refs.append(f"tool:{tool}")
    return ReportSection("Observed", text, source_refs=[r for r in refs if r])


def _obs_from_artifact(obj: Dict[str, Any]) -> ReportSection:
    atype = obj.get("artifact_type") or "artifact"
    rec = obj.get("record") or {}
    summary = (
        rec.get("body")
        or rec.get("text")
        or rec.get("url")
        or rec.get("address")
        or rec.get("number")
        or atype
    )
    summary = str(summary)[:200]
    prov = obj.get("provenance") or {}
    path = prov.get("source_logical_path") or prov.get("source_real_path") or ""
    text = f"Observed {atype}: {summary}."
    refs = [path] if path else []
    return ReportSection("Observed", text, source_refs=refs)


def draft_report(
    *,
    case_id: str = "",
    title: str = "Draft observation report",
    events: Optional[List[Dict[str, Any]]] = None,
    artifacts: Optional[List[Dict[str, Any]]] = None,
    max_observed: int = 200,
) -> DraftReport:
    sections: List[ReportSection] = []
    policy_notes = [
        "Sentence classes limited to Observed, Context, Consistent With, Limitation, Unknown.",
        "No intent, motive, or guilt language is generated by this engine.",
        "Examiner must review and edit before use in any formal product.",
    ]

    sections.append(
        ReportSection(
            "Context",
            "This draft is assembled from structured tool exports only; original evidence files were not opened by Witness Light.",
        )
    )

    events = events or []
    artifacts = artifacts or []
    observed_count = 0

    for ev in events:
        if observed_count >= max_observed:
            break
        sec = _obs_from_event(ev)
        if check_text(sec.text):
            continue
        sections.append(sec)
        observed_count += 1

    for obj in artifacts:
        if observed_count >= max_observed:
            break
        sec = _obs_from_artifact(obj)
        if check_text(sec.text):
            continue
        sections.append(sec)
        observed_count += 1

    # Aggregate context
    types = Counter()
    for ev in events:
        types[str(ev.get("type") or "unknown")] += 1
    for obj in artifacts:
        types[str(obj.get("artifact_type") or "unknown")] += 1
    if types:
        top = ", ".join(f"{k} ({v})" for k, v in types.most_common(8))
        sections.append(
            ReportSection(
                "Context",
                f"Artifact type counts in the supplied export set include: {top}.",
            )
        )

    sections.append(
        ReportSection(
            "Consistent With",
            "The presence of these records is consistent with data having been parsed from device or backup extracts by upstream tools; it is not by itself proof of any particular user action sequence.",
        )
    )
    sections.append(
        ReportSection(
            "Limitation",
            "Timestamps, attribution, and completeness depend on the acquisition method, tool coverage, and source integrity; deleted or unparsed data may be absent.",
        )
    )
    sections.append(
        ReportSection(
            "Limitation",
            "Pattern or identifier matches (if any) are not validated identities without further examination.",
        )
    )
    sections.append(
        ReportSection(
            "Unknown",
            "Whether any listed communication was sent, received, read, or merely stored cannot be determined from this draft alone.",
        )
    )

    # Final policy scan
    for s in sections:
        viol = check_text(s.text)
        if viol:
            policy_notes.append(f"Flagged section ({s.sentence_class}): {', '.join(viol)}")

    return DraftReport(
        title=title,
        case_id=case_id or "unspecified",
        generated_by="WitnessLight/1.0.0",
        sections=sections,
        policy_notes=policy_notes,
        stats={
            "observed_lines": observed_count,
            "events_in": len(events),
            "artifacts_in": len(artifacts),
            "type_counts": dict(types),
        },
    )
