from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List


ALLOWED_CLASSES = (
    "Observed",
    "Context",
    "Consistent With",
    "Limitation",
    "Unknown",
)


@dataclass
class ReportSection:
    sentence_class: str
    text: str
    source_refs: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class DraftReport:
    title: str
    case_id: str
    generated_by: str
    sections: List[ReportSection]
    policy_notes: List[str] = field(default_factory=list)
    stats: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "case_id": self.case_id,
            "generated_by": self.generated_by,
            "sections": [s.to_dict() for s in self.sections],
            "policy_notes": list(self.policy_notes),
            "stats": dict(self.stats),
        }

    def to_text(self) -> str:
        lines = [
            self.title,
            f"Case: {self.case_id}",
            f"Generated by: {self.generated_by}",
            "",
            "This document is a draft of observations and limitations.",
            "It is not a finding of guilt, intent, or legal conclusion.",
            "",
        ]
        current = None
        for s in self.sections:
            if s.sentence_class != current:
                current = s.sentence_class
                lines.append(f"## {current}")
                lines.append("")
            lines.append(f"- {s.text}")
            if s.source_refs:
                lines.append(f"  (refs: {', '.join(s.source_refs[:5])})")
            lines.append("")
        if self.policy_notes:
            lines.append("## Policy")
            lines.append("")
            for n in self.policy_notes:
                lines.append(f"- {n}")
        return "\n".join(lines).rstrip() + "\n"
